/*Find the n’th term in Look-and-say (Or Count and Say) Sequence. The look-and-say sequence is the sequence of the below integers: 
1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, … 
The first term is "1"
Second term is "11", generated by reading first term as "One 1" 
(There is one 1 in previous term)
Third term is "21", generated by reading second term as "Two 1"
Fourth term is "1211", generated by reading third term as "One 2 One 1" 
and so on


*/

function lookandsay(n) {
  if (n === 1) return 1;

  if (n === 2) return 11;

  let str = "11";

  for (let i = 3; i <= n; i++) {
    str += "$";
    let tmp = "",
      count = 1;
    let arr = str.split("");

    for (let j = 1; j < arr.length; j++) {
      if (arr[j] !== arr[j - 1]) {
        tmp += count;
        tmp += arr[j - 1];
        count = 1;
      } else count++;
    }
    str = tmp;
  }

  return str;
}
